#!/usr/bin/env php
<?php

$cli_header_extra = <<< MESSAGE
                      ==============

         ⚠️ The <red>tric</red> command has been replaced with:
                            <yellow>slic</yellow>

             "<red>tric</red>" will continue to work for now.
               You should use "<yellow>slic</yellow>" instead. All
                   the cool kids are doing it.
MESSAGE;

require_once __DIR__ . '/slic.php';